version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "memberstack-devops-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-exik2q38mdg4"
s3_prefix = "memberstack-devops-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
